<a href="https://colab.research.google.com/github/KeerthanaSistla/Sem6DeepLearning/blob/main/DLExternal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. CNN on MNIST Dataset

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import mnist

# Load Dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# Reshape
x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

# CNN Model
model = models.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(10,activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train,y_train,epochs=5)

loss,acc = model.evaluate(x_test,y_test)

print("Accuracy:",acc)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9618 - loss: 0.1258
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9870 - loss: 0.0410
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9919 - loss: 0.0273
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9934 - loss: 0.0202
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9951 - loss: 0.0152
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9899 - loss: 0.0345
Accuracy: 0.9898999929428101


#2. MLP using Types of GD for XOR

In [2]:
import tensorflow as tf
import numpy as np

# XOR Dataset
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]], dtype=np.float32)

y = np.array([[0],
              [1],
              [1],
              [0]], dtype=np.float32)

def create_model():

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation='sigmoid', input_shape=(2,)),
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    return model

optimizers = {

    'BGD': (tf.keras.optimizers.SGD(0.1),4),

    'SGD': (tf.keras.optimizers.SGD(0.1),1),

    'MiniBatchGD': (tf.keras.optimizers.SGD(0.1),2),

    'Momentum': (
        tf.keras.optimizers.SGD(
            learning_rate=0.1,
            momentum=0.9
        ),1
    ),

    'Nesterov': (
        tf.keras.optimizers.SGD(
            learning_rate=0.1,
            momentum=0.9,
            nesterov=True
        ),1
    ),

    'Adagrad': (
        tf.keras.optimizers.Adagrad(0.1),1
    ),

    'RMSProp': (
        tf.keras.optimizers.RMSprop(0.01),1
    ),

    'Adadelta': (
        tf.keras.optimizers.Adadelta(1.0),1
    ),

    'Adam': (
        tf.keras.optimizers.Adam(0.01),1
    )
}

for name,(optimizer,batch_size) in optimizers.items():

    print("\nOptimizer:",name)

    model = create_model()

    model.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    model.fit(
        X,
        y,
        epochs=500,
        batch_size=batch_size,
        verbose=0
    )

    pred = model.predict(X)

    print(np.round(pred))


Optimizer: BGD


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step
[[0.]
 [1.]
 [1.]
 [1.]]

Optimizer: SGD
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step
[[0.]
 [1.]
 [1.]
 [1.]]

Optimizer: MiniBatchGD
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step
[[0.]
 [0.]
 [1.]
 [1.]]

Optimizer: Momentum
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step
[[0.]
 [1.]
 [1.]
 [0.]]

Optimizer: Nesterov


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
[[0.]
 [1.]
 [1.]
 [0.]]

Optimizer: Adagrad


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
[[0.]
 [1.]
 [1.]
 [1.]]

Optimizer: RMSProp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step
[[0.]
 [1.]
 [1.]
 [0.]]

Optimizer: Adadelta
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step
[[0.]
 [1.]
 [0.]
 [0.]]

Optimizer: Adam
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step
[[0.]
 [1.]
 [1.]
 [1.]]


#3. Simple Perceptron

In [3]:
import numpy as np

x = np.array([1,0])
w = np.array([0.5,0.5])
b = -0.2

# Feed Forward
net = np.dot(x,w) + b

# Step Function
def step(z):
    if z >= 0:
        return 1
    return 0

# Sigmoid Function
def sigmoid(z):
    return 1/(1+np.exp(-z))

print("Feed Forward:",net)
print("Step Output:",step(net))
print("Sigmoid Output:",sigmoid(net))

Feed Forward: 0.3
Step Output: 1
Sigmoid Output: 0.574442516811659
